apply plugin: 'com.android.application'

android {
    namespace 'kr.jcb1ee.hackerskeyboard2'
    compileSdkVersion 34
    defaultConfig {
        applicationId 'kr.jcb1ee.hackerskeyboard2'
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 2000000
        versionName "v2.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }
    signingConfigs {
        release {
            storeFile     file(System.getenv("KEYSTORE_PATH") ?: "release.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: ""
            keyAlias      System.getenv("KEY_ALIAS") ?: "hackerskeyboard2"
            keyPassword   System.getenv("KEY_PASSWORD") ?: ""
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
    productFlavors {
    }
    lintOptions {
        checkReleaseBuilds false
    }
}

task generateVersionResource {
    def versionName = android.defaultConfig.versionName
    def outFile = file("src/main/res/values/auto-version.xml")
    outputs.file outFile
    doLast {
        outFile.text = """<?xml version="1.0" encoding="utf-8"?>
<!-- Auto-generated file, do not edit -->
<resources xmlns:xliff="urn:oasis:names:tc:xliff:document:1.2">
   <string name="auto_version">${versionName}</string>
</resources>
"""
    }
}
preBuild.dependsOn generateVersionResource

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == 'org.jetbrains.kotlin' &&
                (details.requested.name == 'kotlin-stdlib-jdk7' ||
                 details.requested.name == 'kotlin-stdlib-jdk8')) {
            details.useTarget("org.jetbrains.kotlin:kotlin-stdlib:1.8.22")
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.google.android.material:material:1.11.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
